import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Goods&Marting",  // Escape single quote
  description: "Generated by create next app",
};

//if pwa worked properly
// if ('serviceWorker' in navigator) {
//   navigator.serviceWorker.register('/sw.js').then(registration => {
//       registration.onupdatefound = () => {
//           const installingWorker = registration.installing;
//           installingWorker.onstatechange = () => {
//               if (installingWorker.state === 'installed') {
//                   // Notify user to refresh
//                   alert('A new version of the app is available. Please refresh the page.');
//               }
//           };
//       };
//   });
// }


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Meta tags, link tags, etc., if any */}
      </head>
      <body className={inter.className}>
        <header></header>  {/* Escape single quote */}
        {children}
      </body>
    </html>
  );
}
