import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Goods&Marting",  // Escape single quote
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Meta tags for the favicon */}
        <link rel="icon" href="./favicon.ico" type="image/x-icon" />
        {/* You can add additional favicons for different sizes/types if needed */}
        {/* <link rel="apple-touch-icon" href="/apple-touch-icon.png" /> */}
        <link rel="icon" sizes="192x192" href="./favicon.ico" />
      </head>
      <body className={inter.className}>
        <header></header>  {/* Escape single quote */}
        {children}
      </body>
    </html>
  );
}
